[2014-03-20 18:08:01.205572]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 1551, in lineReceived
    self.allContentReceived()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 1618, in allContentReceived
    req.requestReceived(command, path, version)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 773, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/server.py", line 132, in process
    self.render(resrc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/server.py", line 167, in render
    body = resrc.render(self)
  File "/Users/Psyko/Desktop/Soccer/app/admin/handle.py", line 41, in render
    data=getStatistics()
  File "/Users/Psyko/Desktop/Soccer/app/admin/urls.py", line 76, in getStatistics
    cursor.execute(sql4)
  File "/Library/Python/2.7/site-packages/DBUtils-1.1-py2.7.egg/DBUtils/SteadyDB.py", line 631, in tough_method
    raise error # reraise the original error again
_mysql_exceptions.OperationalError: (1054, "Unknown column 'rmb' in 'field list'")

[2014-03-20 18:09:27.917515]
ERROR
	Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 1551, in lineReceived
    self.allContentReceived()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 1618, in allContentReceived
    req.requestReceived(command, path, version)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/http.py", line 773, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/server.py", line 132, in process
    self.render(resrc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/web/server.py", line 167, in render
    body = resrc.render(self)
  File "/Users/Psyko/Desktop/Soccer/app/admin/handle.py", line 33, in render
    index=int(request.args['index'][0])
exceptions.KeyError: 'index'

